const REGISTER_API_CALL_REQUEST = "REGISTER_API_CALL_REQUEST";
const REGISTER_API_CALL_SUCCESS = "REGISTER_API_CALL_SUCCESS";
const REGISTER_API_CALL_FAILURE = "REGISTER_API_CALL_FAILURE";
export {
    REGISTER_API_CALL_REQUEST,
    REGISTER_API_CALL_SUCCESS,
    REGISTER_API_CALL_FAILURE
}