const LOGIN_API_CALL_REQUEST = "LOGIN_API_CALL_REQUEST";
const LOGIN_API_CALL_SUCCESS = "LOGIN_API_CALL_SUCCESS";
const LOGIN_API_CALL_FAILURE = "LOGIN_API_CALL_FAILURE";
export {
    LOGIN_API_CALL_REQUEST,
    LOGIN_API_CALL_SUCCESS,
    LOGIN_API_CALL_FAILURE
}